---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-database
  namespace: minecraft-dev
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: mariadb
      version: 11.1.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   repository: bitnami/mariadb
    #   tag: 10.5.12-debian-10-r74
    auth:
      rootPassword: pixelmontogo
      database: pixelmontogo
    primary:
      extraFlags: "--max_connections=500"
      persistence:
        enabled: true
        storageClass: longhorn
        size: 2Gi
