---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-database
  namespace: minecraft-dev
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 10.3.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    # image:
    #   repository: bitnami/mariadb
    #   tag: 10.6.5-debian-10-r74
    auth:
      rootPassword: pixelmontogo
      database: pixelmontogo
    primary:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 2Gi
