---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-forge-celebi
  namespace: minecraft-dev
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.8.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    nameOverride: dev
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: pixelmontogo.com/region
              operator: In
              values:
                - england
                - france
                - germany
    image: itzg/minecraft-server
    imageTag: 2022.4.1-java8-openj9
    persistence:
      storageClass: longhorn-emea
      dataDir:
        enabled: true
        Size: 100Gi
    resources:
      requests:
        memory: 21Gi
      limits:
        memory: 25Gi
    extraEnv:
      FORCE_GENERIC_PACK_UPDATE: "TRUE"
      GENERIC_PACKS_SUFFIX: "forge-v10.1.0+es.zip"
      REPLACE_ENV_VARIABLES: "TRUE"
      REPLACE_ENV_VARIABLES_EXCLUDE_PATHS: "/data/pixelmon /data/config/aquadaycare/decorations"
      CFG_VC_HOST: "celebi-vc-dev.pixelmonreforged.com"
      CFG_GTS_DB: "celebiglobaltrade"
      CFG_ECONOMY_DB: "celebieconomylite"
      CFG_REFORGED_GTS_DB: "celebireforgedgts"
      CFG_WONDERTRADE_DB: "celebiwondertrade"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
      ALLOW_FLIGHT: "true"
    livenessProbe:
      initialDelaySeconds: 360
    readinessProbe:
      initialDelaySeconds: 200
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.12.2"
      jvmOpts: "-Xmns3G -Xmnx7G -Xgcpolicy:balanced -Xdisableexplicitgc -Dfml.readTimeout=300 -Dmixin.debug=true"
      forgeVersion: "14.23.5.2860"
      gameMode: "0"
      forcegameMode: false
      type: FORGE
      pvp: false
      forceReDownload: true
      difficulty: "0"
      levelType: OTG
      playerIdleTimeout: 300
      spawnProtection: 0
      maxWorldSize: 29999984
      maxPlayers: 120
      viewDistance: 4
      maxTickTime: -1
      memory: 14G
      motd: "forge-celebi"
      overrideServerProperties: true
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      extraPorts:
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: voice
          containerPort: 24454
          protocol: UDP
          service:
            enabled: true
            annotations:
              external-dns.alpha.kubernetes.io/hostname: celebi-vc-dev.pixelmonreforged.com
              # metallb.universe.tf/address-pool: germany
            type: LoadBalancer
            port: 24454
          ingress:
            enabled: false
  valuesFrom:
    - kind: Secret
      name: "minecraft-forge-pikachu-helm-values"
