---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft-dev
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: dev
    image: itzg/bungeecord
    imageTag: java17-2022.1.0
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: proxy-dev.pixelmonreforged.com,pikachu-dev.pixelmonreforged.com,celebi-dev.pixelmonreforged.com
      metallb.universe.tf/address-pool: canada
    strategyType: Recreate
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 3.1.1
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      memory: 512M
      jvmOpts: "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED -Dlog4j2.formatMsgNoLookups=true"
      extraPorts:
        - name: vote
          containerPort: 8192
          service:
            enabled: true
            embedded: true
            port: 8192
          ingress:
            enabled: false
        - name: prometheus
          containerPort: 9100
          service:
            enabled: true
            port: 9100
            type: ClusterIP
          ingress:
            enabled: false
