---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-lobby-kanto
  namespace: minecraft-dev
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.8.2
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    image: itzg/minecraft-server
    imageTag: 2022.4.1-java8-multiarch
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 15Gi
      limits:
        memory: 16Gi
    extraEnv:
      DD_ENV: "dev"
      DD_SERVICE: "kanto"
      DD_PROFILING_ENABLED: "true"
      DD_LOGS_INJECTION: "true"
      DD_APPSEC_ENABLED: "true"
      ENABLE_JMX: "true"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
      TUNE_NURSERY_SIZES: "TRUE"
      TUNE_VIRTUALIZED: "TRUE"
      ENABLE_ROLLING_LOGS: "TRUE"
      STOP_SERVER_ANNOUNCE_DELAY: "15"
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.12.2"
      jvmOpts: "-javaagent:dd-java-agent.jar"
      jvmXXOpts: "-XX:FlightRecorderOptions=stackdepth=256"
      mode: "2"
      forcegameMode: true
      type: PAPER
      pvp: false
      allowNether: false
      forceReDownload: false
      difficulty: "0"
      maxPlayers: 120
      maxWorldSize: 100000
      viewDistance: 8
      maxTickTime: -1
      memory: 8G
      motd: "lobby-kanto"
      overrideServerProperties: true
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      extraPorts:
        - name: jmx
          containerPort: 7091
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 7091
          ingress:
            enabled: false
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
