---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft-dev
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - echo-i2-lim3
    nameOverride: dev
    image: itzg/bungeecord
    imageTag: java8
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: proxy-dev.pixelmonreforged.com
      metallb.universe.tf/address-pool: canada
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 1.1.5
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      memory: 512M
      extraPorts:
        - name: vote
          containerPort: 8192
          service:
            enabled: true
            embedded: true
            port: 8192
          ingress:
            enabled: false
