---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft-dev
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minecraft-proxy
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: dev
    image:
      repository: itzg/bungeecord
      tag: java17-2022.1.0
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: proxy-dev.pixelmonreforged.com,pikachu-dev.pixelmonreforged.com,celebi-dev.pixelmonreforged.com
      metallb.universe.tf/address-pool: canada
    strategyType: Recreate
    extraEnv:
      VELOCITY_BUILD_ID: 138
      JMX_HOST:
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      DD_AGENT_HOST:
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      DD_ENV: "dev"
      DD_SERVICE: "velocity"
      DD_VERSION: "$(VELOCITY_VERSION)#$(VELOCITY_BUILD_ID)"
      DD_PROFILING_ENABLED: "true"
      DD_LOGS_INJECTION: "true"
      DD_APPSEC_ENABLED: "true"
      JVM_XX_OPTS: "-XX:FlightRecorderOptions=stackdepth=256 -javaagent:dd-java-agent.jar -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=7091 -Dcom.sun.management.jmxremote.rmi.port=7091 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=0.0.0.0 -Djava.rmi.server.hostname=$(JMX_HOST)"
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 3.1.2-SNAPSHOT
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      memory: 512M
      jvmOpts: "--add-exports=java.base/sun.nio.ch=ALL-UNNAMED -Dlog4j2.formatMsgNoLookups=true -Dvelocity.natives-disabled=true -Dvelocity.disable-native-transport=true"
      extraPorts:
        - name: vote
          containerPort: 8192
          service:
            enabled: true
            embedded: true
            port: 8192
          ingress:
            enabled: false
        - name: prometheus
          containerPort: 9100
          service:
            enabled: true
            port: 9100
            type: ClusterIP
          ingress:
            enabled: false
