---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: kube-system
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: external-dns
      version: 6.1.5
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    provider: cloudflare
    cloudflare:
      email: pixelmontogo@jhlws.com
      secretName: cloudflare-api-key
      proxied: false
    domainFilters: ["pixelmonreforged.com"]
    policy: sync
