---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-operator
  namespace: rook-ceph
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph
      version: v1.9.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    nodeSelector:
      kubernetes.io/hostname: alpha-i2-sbg3
    tolerations:
      - key: "rook-test"
        operator: "Exists"
    admissionController:
      tolerations:
        - key: "rook-test"
          operator: "Exists"
      nodeAffinity: kubernetes.io/hostname=alpha-i2-sbg3
    crds:
      enabled: true
    csi:
      provisionerNodeAffinity: kubernetes.io/hostname=alpha-i2-sbg3
      provisionerTolerations:
        - key: "rook-test"
          operator: "Exists"
      pluginNodeAffinity: kubernetes.io/hostname=alpha-i2-sbg3
      pluginTolerations:
        - key: "rook-test"
          operator: "Exists"
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
