---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: datadog
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.datadoghq.com
      chart: datadog
      version: 2.22.18
      sourceRef:
        kind: HelmRepository
        name: datadog-charts
        namespace: flux-system
      interval: 5m
  values:
    # agents:
    #   image:
    #     repository: ghcr.io/architectsmp/datadog-agent
    #     tag: latest
    datadog:
      apm:
        enabled: true
      clusterAgent:
        enabled: true
        metricsProvider:
          enabled: true
      criSocketPath: /var/run/k3s/containerd/containerd.sock
      logs:
        enabled: true
        containerCollectAll: true
      networkMonitoring:
        enabled: true
      processAgent:
        enabled: true
        processCollection: true
      prometheusScrape:
        enabled: true
      site: datadoghq.eu
    kubeStateMetricsEnabled: false
    targetSystem: linux
  valuesFrom:
    - kind: Secret
      name: "datadog-helm-values"
      optional: false
