---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy-bravo
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.1.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: prod
    image: itzg/bungeecord
    imageTag: java8
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    minecraftProxy:
      type: VELOCITY
      serviceType: LoadBalancer
      loadBalancerIP: 54.36.241.28
      externalTrafficPolicy: Local
      memory: 2G
      extraPorts:
        - name: vote
          containerPort: 8192
          service:
            enabled: true
            annotations:
              metallb.universe.tf/allow-shared-ip: bravo-proxy
            type: LoadBalancer
            loadBalancerIP: 54.36.241.28
            port: 8192
          ingress:
            enabled: false
    serviceAnnotations:
      metallb.universe.tf/allow-shared-ip: bravo-proxy
