---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy-bravo
  namespace: minecraft
spec:
  interval: 5m
  chart:
    spec:
      chart: ./releases/minecraft-proxy-2.2.0.tgz
      sourceRef:
        kind: GitRepository
        name: ptg-minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - ns31354176
    nameOverride: prod
    image: itzg/bungeecord
    imageTag: java8
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 1.1.5
      serviceType: LoadBalancer
      loadBalancerIP: 54.36.241.28
      externalTrafficPolicy: Local
      memory: 2G
      extraPorts:
        - name: vote
          containerPort: 8192
          service:
            enabled: true
            embedded: true
            port: 8192
          ingress:
            enabled: false
