---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-proxy
  namespace: minecraft
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      chart: minecraft-proxy
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: pixelmontogo.com/region
                  operator: In
                  values:
                    - germany
                    - france
    nameOverride: prod
    image: itzg/bungeecord
    imageTag: java8
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: proxy.pixelmonreforged.com
      metallb.universe.tf/address-pool: germany
    minecraftProxy:
      type: VELOCITY
      velocityVersion: 1.1.5
      serviceType: LoadBalancer
      externalTrafficPolicy: Local
      memory: 2G
      extraPorts:
        - name: vote
          containerPort: 8192
          service:
            enabled: true
            embedded: true
            port: 8192
          ingress:
            enabled: false
