---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-database
  namespace: minecraft
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: mariadb
      version: 10.2.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
    # image:
    #   repository: bitnami/mariadb
    #   tag: 10.5.12-debian-10-r74
    auth:
      rootPassword: pixelmontogo
      database: pixelmontogo
    primary:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: pixelmontogo.com/region
                    operator: In
                    values:
                      - germany
                      - france
                      - england
      podAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - minecraft-forge-charmander-prod
              topologyKey: kubernetes.io/hostname
      extraFlags: "--max_connections=500"
      persistence:
        enabled: true
        storageClass: longhorn
        size: 8Gi
