---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minecraft-lobby-kanto
  namespace: minecraft
spec:
  interval: 5m
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 3.7.2
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    # ref: https://github.com/itzg/minecraft-server-charts/blob/master/charts/minecraft/values.yaml
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
                - key: pixelmontogo.com/region
                  operator: In
                  values:
                    - england
                    - france
                    - germany
    nameOverride: prod
    image: itzg/minecraft-server
    imageTag: 2022.1.1-java8-openj9
    persistence:
      storageClass: longhorn
      dataDir:
        enabled: true
        Size: 10Gi
    resources:
      requests:
        memory: 15Gi
      limits:
        memory: 16Gi
    extraEnv:
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      NETWORK_COMPRESSION_THRESHOLD: "-1"
      TUNE_NURSERY_SIZES: "TRUE"
      TUNE_VIRTUALIZED: "TRUE"
    minecraftServer:
      eula: "TRUE"
      onlineMode: false
      version: "1.12.2"
      mode: "2"
      forcegameMode: true
      type: PAPER
      pvp: false
      allowNether: false
      forceReDownload: false
      difficulty: "0"
      maxPlayers: 120
      maxWorldSize: 100000
      viewDistance: 8
      maxTickTime: -1
      memory: 8G
      motd: "lobby-kanto"
      serviceType: ClusterIP
      rcon:
        enabled: true
        serviceType: ClusterIP
      extraPorts:
        - name: prometheus
          containerPort: 9225
          service:
            enabled: true
            annotations: {}
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
