---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: 2.6.5
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 5m
  values:
    loki:
      config:
        table_manager:
          retention_deletes_enabled: true
          retention_period: 336h
      persistence:
        enabled: true
        storageClassName: "longhorn"
        size: 25Gi
      serviceMonitor:
        enabled: true
    promtail:
      serviceMonitor:
        enabled: true
