---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: ptg-minecraft-server-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/pixelmontogo/minecraft-server-charts
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include releases directory
    !/releases/
