{
 "title": "1 PTG Minecraft",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values(mc_tps, container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Volume Space Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  kubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"minecraft.+\"}\n  -\n  kubelet_volume_stats_available_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"minecraft.+\"}\n)\n/\nkubelet_volume_stats_capacity_bytes{job=\"kubelet\", metrics_path=\"/metrics\", persistentvolumeclaim=~\"minecraft.+\"}\n* 100\n",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Average TPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mc_tps{container=~\"$container\"} > 1"
    }
   ]
  },
  {
   "title": "Loaded Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mc_loaded_chunks_total{container=~\"$container\"}",
     "legendFormat": "{{world}}"
    }
   ]
  },
  {
   "title": "Network usage per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps", "label": "transmit (-) / receive (+)" }
   ],
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))\n",
     "legendFormat": "{{workload}}_receive"
    },
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))\n",
     "legendFormat": "{{workload}}_transmit"
    },
    {
     "expr": "(sum(irate(container_network_receive_packets_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))",
     "legendFormat": "{{workload}}_receive_count"
    },
    {
     "expr": "(sum(irate(container_network_transmit_packets_total[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{workload=~\"$container\", workload_type=\"deployment\"}) by (workload))",
     "legendFormat": "{{workload}}_transmit_count"
    }
   ]
  },
  {
   "title": "Entity Counts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (mc_entities_total{container=~\"$container\"}) by (world)",
     "legendFormat": "{{world}}_total"
    }
   ]
  },
  {
   "title": "Tickrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mc_tps{container=~\"$container\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Entities",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (mc_entities_total{container=~\"$container\"} > 5) by (world, level, type)",
     "legendFormat": "{{world}}:  {{type}}"
    }
   ]
  },
  {
   "title": "Tick Durations",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mc_tick_duration_max{container=~\"$container\"}/1e6",
     "legendFormat": "Max - {{container}}"
    },
    {
     "expr": "mc_tick_duration_average{container=~\"$container\"}/1e6",
     "legendFormat": "Avg - {{container}}"
    }
   ]
  }
 ]
}