{
 "title": "1 PTG Pregen",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chunks Processed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time({job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |=\"World generation is now at\" | regexp `.*%\\. \\((?P<chunks_complete>.*)\\/` | unwrap chunks_complete [1m]) without (job, filename)"
    }
   ]
  },
  {
   "title": "Percent Complete",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time({job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |=\"World generation is now at\" | regexp `.*now at (?P<percent_complete>.*)%` | unwrap percent_complete [1m]) without (job, filename)"
    }
   ]
  },
  {
   "title": "Chunks Remaining",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "9765625 - max_over_time({job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |=\"World generation is now at\" | regexp `.*%\\. \\((?P<chunks_complete>.*)\\/` | unwrap chunks_complete [1m]) without (job, filename)"
    }
   ]
  },
  {
   "title": "Estimated Time Remaining",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((9765625 - max_over_time({job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |=\"World generation is now at\" | regexp `.*%\\. \\((?P<chunks_complete>.*)\\/` | unwrap chunks_complete [1m]) without (job, filename)) / (max_over_time({job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |=\"World generation is now at\" | regexp `.*%\\. \\((?P<chunks_complete>.*)\\/` | unwrap chunks_complete [4h]) without (job, filename) - min_over_time({job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |=\"World generation is now at\" | regexp `.*%\\. \\((?P<chunks_complete>.*)\\/` | unwrap chunks_complete [4h]) without (job, filename))) *4*60*60"
    }
   ]
  },
  {
   "title": "Squirtle Pregen",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "{job=\"minecraft-dev/minecraft-forge-charmander-dev\"} |~\"World generation is now at\""
    }
   ]
  },
  {
   "title": "Squirtle Pregen",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "{job=\"minecraft-dev/minecraft-forge-charmander-dev\"}"
    }
   ]
  }
 ]
}