{
 "title": "1 PTG Network",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Client Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"minecraft/minecraft-proxy-prod\"} |~\"has connected\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Client Disconnections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"minecraft/minecraft-proxy-prod\"}[$__interval] |~\"has disconnected\"))"
    }
   ]
  },
  {
   "title": "Proxy Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"minecraft/minecraft-proxy-prod\"} !=\"INFO]\""
    }
   ]
  },
  {
   "title": "Proxy Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"minecraft/minecraft-forge-charmander-prod\"}"
    }
   ]
  },
  {
   "title": "Charmander Logs",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
   "valueName": "total",
   "targets": [
    {
     "expr": "count without (IP) (sum by (IP, geoip_country_code) (count_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"[mask]\" |~\"logged in from\" | regexp `logged in from \\\"(?P<IP>.*)\\\".*location \\\"(?P<geoip_country_code>[A-Z][A-Z])\\\"`[$__interval])))",
     "legendFormat": "{{geoip_country_code}}"
    }
   ]
  }
 ]
}