{
 "title": "1 PTG Voice",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Average Average",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"Distance Calculations\" | regexp `.*average was\\: (?P<voice_avg>.*) overall` | unwrap voice_avg [1m]) without (pod, filename)"
    }
   ]
  },
  {
   "title": "Maximum Average",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"Distance Calculations\" | regexp `.*average was\\: (?P<voice_avg>.*) overall` | unwrap voice_avg [1m]) without (pod, filename)"
    }
   ]
  },
  {
   "title": "Average Overall",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"Distance Calculations\" | regexp `.*overall was\\: (?P<voice_tot>.*)$` | unwrap voice_tot [1m]) without (pod, filename)"
    }
   ]
  },
  {
   "title": "Maximum Overall",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"Distance Calculations\" | regexp `.*overall was\\: (?P<voice_tot>.*)$` | unwrap voice_tot [1m]) without (pod, filename)"
    }
   ]
  },
  {
   "title": "Charmander Voice",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{job=\"minecraft/minecraft-forge-charmander-prod\"} |~\"Distance Calculations\""
    }
   ]
  },
  {
   "title": "Timings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"Distance Calculations\" | regexp `.*average was\\: (?P<voice_avg>.*) overall` | unwrap voice_avg [1m])"
    },
    {
     "expr": "max_over_time({job=\"minecraft/minecraft-forge-charmander-prod\"} |=\"Distance Calculations\" | regexp `.*overall was\\: (?P<voice_tot>.*)$` | unwrap voice_tot [1m])"
    }
   ]
  }
 ]
}