---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: thanos
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: thanos
      version: 10.3.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      storageClass: longhorn
    query:
      enabled: true
      replicaCount: 2
      replicaLabels:
        - replica
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: monitoring
      ingress:
        enabled: true
        hostname: thanos.pixelmonreforged.com
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/auth-url: "https://login.pixelmonreforged.com/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: https://login.pixelmonreforged.com/oauth2/start
        tls: true
    queryFrontend:
      enabled: false
    bucketweb:
      enabled: true
    compactor:
      enabled: true
      persistence:
        enabled: false
    storegateway:
      enabled: true
      persistence:
        enabled: true
        size: 20Gi
    ruler:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  valuesFrom:
    - kind: Secret
      name: "thanos-helm-values"
      optional: false
