---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-router
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.enix.io/
      chart: kube-router
      version: 1.4.1
      sourceRef:
        kind: HelmRepository
        name: enix-charts
        namespace: flux-system
      interval: 5m
