---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: kube-system
spec:
  interval: 5m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: vault-secrets-operator
      version: 1.17.0
      sourceRef:
        kind: HelmRepository
        name: ricoberger-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 1
    deploymentStrategy:
      type: Recreate
    vault:
      address: "http://vault:8200"
      authMethod: kubernetes
      kubernetesPath: auth/kubernetes
      kubernetesRole: vault-secrets-operator
      reconciliationTime: "300"
