---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  install:
    crds: Create
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  chart:
    spec:
      chart: longhorn
      version: 1.2.3
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClassReplicaCount: 2
    defaultSettings:
      defaultDataPath: /longhorn
      defaultReplicaCount: 3
      defaultDataLocality: best-effort
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      createDefaultDiskLabeledNodes: true
      storageMinimalAvailablePercentage: "10"
      backupTarget: s3://longhorn@us-east-1/
      backupTargetSecret: minio-secret
    ingress:
      enabled: true
      host: longhorn.pixelmonreforged.com
      tlsSecret: longhorn-cert
      tls: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        nginx.ingress.kubernetes.io/auth-url: https://login.pixelmonreforged.com/oauth2/auth
        nginx.ingress.kubernetes.io/auth-signin: https://login.pixelmonreforged.com/oauth2/start
