---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-amer
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  nodeSelector: "amer"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-emea
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "480"
  nodeSelector: "emea"
