---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: minio-secret
  namespace: longhorn-system
spec:
  keys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
    - AWS_ENDPOINTS
  path: secrets/longhorn-system/longhorn/minio-secret
  type: Opaque
