---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: insights-agent
  namespace: fairwinds
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      chart: insights-agent
      version: 2.0.3
      sourceRef:
        kind: HelmRepository
        name: fairwinds-stable-charts
        namespace: flux-system
      interval: 5m
  values:
    insights:
      organization: "wolf"
      cluster: "stg"
    goldilocks:
      enabled: true
    kubebench:
      enabled: false # TODO: k3s support
    kubesec:
      enabled: true
    polaris:
      enabled: true
    resourcemetrics:
      enabled: true
      address: "http://thanos-query.monitoring"
    trivy:
      enabled: true
  valuesFrom:
    - kind: Secret
      name: "insights-agent-helm-values"
