---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 5m
  values:
    controller:
      replicaCount: 1
      dnsConfig:
        nameservers:
          - 9.9.9.9
      config:
        custom-http-errors: 404,401,403,500,503
        hsts-max-age: "31449600"
      use-forwarded-headers: "true"
      service:
        annotations:
          metallb.universe.tf/address-pool: germany
        externalTrafficPolicy: Local
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
          namespace: kube-system
        prometheusRule:
          enabled: false
      extraArgs:
        default-ssl-certificate: "cert-manager/acme-crt-secret"
      resources:
        requests:
          memory: 500Mi
          cpu: 25m
        limits:
          memory: 600Mi
    defaultBackend:
      enabled: true
      image:
        repository: billimek/custom-error-pages
        tag: 0.4.4
      resources:
        requests:
          memory: 250Mi
          cpu: 25m
        limits:
          memory: 350Mi
