---
name: Fairwinds Insights

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FAIRWINDS_TOKEN: ${{ secrets.FAIRWINDS_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Fairwinds Insights
        continue-on-error: true
        run: |
          curl -L https://raw.githubusercontent.com/FairwindsOps/insights-plugins/main/ci-script.sh > insights-ci.sh
          chmod +x insights-ci.sh
          ./insights-ci.sh
