---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 2.6.14
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      address-pools:
        - name: canada
          protocol: layer2
          addresses:
            - 51.222.234.145
            - 51.222.234.147-51.222.234.149
        - name: england
          protocol: layer2
          addresses:
            - 51.68.223.178-51.68.223.181
        - name: france
          protocol: layer2
          addresses:
            - 54.36.241.26-54.36.241.29
        - name: germany
          protocol: layer2
          addresses:
            - 141.95.31.90-141.95.31.93
        - name: singapore
          protocol: layer2
          addresses:
            - 139.99.35.137-139.99.35.141
    networkPolicy:
      enabled: true
    prometheusRule:
      enabled: true
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.12.1
      prometheus:
        serviceMonitor:
          enabled: false
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.12.1
      prometheus:
        serviceMonitor:
          enabled: false
