---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.bitnami.com/bitnami
      chart: metallb
      version: 2.5.9
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  values:
    configInline:
      address-pools:
        - name: canada
          protocol: layer2
          addresses:
            - 51.222.234.147-51.222.234.149
        - name: germany
          protocol: layer2
          addresses:
            - 141.95.31.91-141.95.31.93
    networkPolicy:
      enabled: true
    prometheusRule:
      enabled: true
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.11.0
      prometheus:
        serviceMonitor:
          enabled: true
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.11.0
      prometheus:
        serviceMonitor:
          enabled: true
